# Generated by Django 6.0.2 on 2026-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_semesters',
            field=models.IntegerField(default=6, help_text='Total number of semesters for this course'),
        ),
    ]
