# Generated by Django 6.0.2 on 2026-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtimetable',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
