# Generated by Django 6.0.2 on 2026-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentprofile_admission_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Technology', 'Technology'), ('Management', 'Management'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
