# Generated by Django 6.0.2 on 2026-03-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('course', models.CharField(choices=[('BCA', 'Bachelor of Computer Applications (BCA)'), ('MCA', 'Master of Computer Applications (MCA)'), ('MBA', 'Master of Business Administration (MBA)')], max_length=10)),
                ('subject_marks', models.TextField(help_text="Enter marks one per line in format 'Subject Name: Marks'. E.g., 'Java: 85'")),
                ('total_marks', models.IntegerField()),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
