# Generated by Django 6.0.2 on 2026-03-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='centre_code',
            field=models.CharField(blank=True, help_text='Study Centre Code (Optional)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_name',
            field=models.CharField(choices=[('SEP 2025 Special Exam', 'SEP 2025 Special Exam'), ('APR 2025 Regular Exam', 'APR 2025 Regular Exam'), ('DEC 2024 Arrear Exam', 'DEC 2024 Arrear Exam')], default='APR 2025 Regular Exam', max_length=100),
        ),
    ]
