# Generated by Django 6.0.2 on 2026-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_studentresult_centre_code_studentresult_exam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty_name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
