# Generated by Django 6.0.2 on 2026-04-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('MBA', 'MBA')], max_length=10)),
                ('exam_name', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Exam', 'Final Exam')], max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('duration', models.CharField(help_text='e.g. 2 Hours, 3 Hours', max_length=50)),
                ('room_number', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
    ]
