# Generated by Django 6.0.2 on 2026-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_examschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g. 2 Hours', max_length=50, null=True),
        ),
    ]
