# Generated by Django 6.0.2 on 2026-04-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_timetable_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField()),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_school', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
                ('admission_year', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='admission_docs/')),
                ('marksheet', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='admission_docs/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_max', models.IntegerField(default=100)),
                ('theory_min', models.IntegerField(default=35)),
                ('theory_marks', models.IntegerField(default=0)),
                ('practical_max', models.IntegerField(default=50)),
                ('practical_min', models.IntegerField(default=15)),
                ('practical_marks', models.IntegerField(default=0)),
                ('internal_marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('result_status', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Backlog', 'Backlog')], default='Pass', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='core.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='core.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
